events {
    worker_connections 1024;
}

http {
    upstream security_service {
        server security:8081;
    }

    upstream uploader_service {
        server uploader:8082;
    }

    upstream minio_service {
        server minio:9000;
    }

    server {
        listen 80;
        server_name localhost;

        location = /_validate_token {
            internal;
            proxy_pass http://security_service/v1/token/validation/;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
        }

        location @unauthorized {
            return 401 '{"error":"Unauthorized"}';
            add_header Content-Type application/json;
        }

        location = /v1/register {
            proxy_pass http://security_service/v1/user;
        }

        location = /v1/token {
            proxy_pass http://security_service/v1/token;
        }

        location = /v1/user {
            auth_request /_validate_token;
            error_page 401 = @unauthorized;
            proxy_pass http://security_service/v1/user;
            proxy_set_header Authorization $http_authorization;
        }

        location = /v1/upload {
            auth_request /_validate_token;
            error_page 401 = @unauthorized;
            proxy_pass http://uploader_service/v1/upload;
            proxy_set_header Authorization $http_authorization;
            client_max_body_size 50M;
        }

        location ~ ^/v1/user/(.+)$ {
            auth_request /_validate_token;
            error_page 401 = @unauthorized;
            set $image_name $1;
            proxy_pass http://minio_service/images/$image_name;
            proxy_set_header Host minio:9000;
        }
    }
}
